# Generated by Django 2.2 on 2019-05-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modernaize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_height',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image_width',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
