# Generated by Django 2.0.1 on 2019-06-12 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modernaize', '0002_auto_20190611_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemetadata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
